In [1]:
import pandas as pd

In [13]:
df = pd.read_stata("../../data/mtus/MTUS_haf.dta")
df

,country,survey,svyregion,hldid,persid,id,sex,age,day,badcase,...,volorgwk,commute,travel,sportex,tvradio,read,compint,goout,leisure,missing
0,Argentina,2021.0,National sample,100000.0,1.000000e+00,1.0,Woman,24.0,unspecified weekend day,good quality diary,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0,0.0
1,Argentina,2021.0,National sample,100001.0,1.000000e+00,1.0,Man,68.0,unspecified weekday,good quality diary,...,0.0,0.0,0.0,0.0,210.0,0.0,0.0,0.0,240.0,0.0
2,Argentina,2021.0,National sample,100012.0,1.000000e+00,1.0,Woman,39.0,unspecified weekday,good quality diary,...,0.0,60.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0
3,Argentina,2021.0,National sample,100014.0,3.000000e+00,1.0,Man,14.0,unspecified weekday,good quality diary,...,0.0,80.0,0.0,0.0,0.0,0.0,90.0,0.0,0.0,0.0
4,Argentina,2021.0,National sample,100021.0,2.000000e+00,1.0,Woman,34.0,unspecified weekday,good quality diary,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429248,United States,2023.0,National sample,20231212232082.0,2.023121e+13,1.0,Woman,68.0,Saturday,good quality diary,...,0.0,0.0,90.0,0.0,120.0,0.0,0.0,240.0,0.0,0.0
1429249,United States,2023.0,National sample,20231212232141.0,2.023121e+13,1.0,Man,80.0,Saturday,good quality diary,...,0.0,0.0,112.0,0.0,255.0,0.0,90.0,0.0,253.0,0.0
1429250,United States,2023.0,National sample,20231212232214.0,2.023121e+13,1.0,Woman,67.0,Monday,good quality diary,...,0.0,0.0,0.0,0.0,0.0,0.0,195.0,0.0,90.0,0.0
1429251,United States,2023.0,National sample,20231212232271.0,2.023121e+13,1.0,Man,65.0,Monday,good quality diary,...,0.0,0.0,165.0,0.0,235.0,0.0,0.0,150.0,0.0,0.0
1429252,United States,2023.0,National sample,20231212232280.0,2.023121e+13,1.0,Man,29.0,Tuesday,there is more than one condition missing,...,0.0,0.0,0.0,0.0,660.0,0.0,0.0,0.0,0.0,0.0

# Get France Results - Demographic and time (daily weekday and daily weekend times)

In [ ]:
df = df[df["country"] == "France"]
df = df[df["survey"] == 2009]
df

,country,survey,svyregion,hldid,persid,id,sex,age,day,badcase,...,volorgwk,commute,travel,sportex,tvradio,read,compint,goout,leisure,missing
293114,France,2009.0,National sample,1.0,1.0,1.0,Woman,57.0,Monday,good quality diary,...,30.0,30.0,20.0,0.0,200.0,40.0,0.0,0.0,80.0,0.0
293115,France,2009.0,National sample,1.0,2.0,1.0,Man,59.0,Monday,good quality diary,...,20.0,40.0,0.0,0.0,170.0,20.0,0.0,0.0,50.0,0.0
293116,France,2009.0,National sample,2.0,1.0,1.0,Woman,81.0,Thursday,good quality diary,...,0.0,0.0,0.0,0.0,400.0,0.0,0.0,0.0,40.0,0.0
293117,France,2009.0,National sample,2.0,1.0,2.0,Woman,81.0,Sunday,good quality diary,...,0.0,0.0,0.0,0.0,410.0,0.0,0.0,0.0,80.0,0.0
293118,France,2009.0,National sample,3.0,1.0,1.0,Man,78.0,Friday,good quality diary,...,0.0,0.0,30.0,0.0,160.0,60.0,0.0,130.0,60.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321012,France,2009.0,National sample,10674.0,2.0,2.0,Woman,49.0,Sunday,good quality diary,...,0.0,0.0,130.0,0.0,260.0,0.0,0.0,0.0,60.0,0.0
321013,France,2009.0,National sample,10675.0,1.0,1.0,Man,59.0,Saturday,good quality diary,...,0.0,0.0,30.0,0.0,180.0,0.0,0.0,0.0,60.0,0.0
321014,France,2009.0,National sample,10675.0,1.0,2.0,Man,59.0,Friday,good quality diary,...,190.0,0.0,100.0,0.0,0.0,0.0,120.0,0.0,300.0,0.0
321015,France,2009.0,National sample,10675.0,2.0,1.0,Woman,54.0,Saturday,good quality diary,...,0.0,0.0,50.0,90.0,110.0,0.0,60.0,0.0,80.0,0.0
321016,France,2009.0,National sample,10675.0,2.0,2.0,Woman,54.0,Friday,good quality diary,...,0.0,0.0,50.0,20.0,60.0,0.0,30.0,0.0,30.0,0.0

In [ ]:
demographic_cols = ["SEX", "AGE", "DAY", "HHTYPE", "EDCAT", "HEALTH", "VEHICLE"]
demographic_cols = [col.lower() for col in demographic_cols]

time_use_cols = [
    "SLEEP", "EATDRINK", "SELFCARE", "PAIDWORK", "EDUCATN", 
    "FOODPREP", "CLEANETC", "MAINTAIN", "SHOPSERV", "GARDEN", 
    "PETCARE", "ELDCARE", "PKIDCARE", "IKIDCARE", "RELIGION", 
    "VOLORGWK", "COMMUTE", "TRAVEL", "SPORTEX", "TVRADIO", 
    "READ", "COMPINT", "GOOUT", "LEISURE", "MISSING"
]
time_use_cols = [col.lower() for col in time_use_cols]

final_cols = demographic_cols + time_use_cols

In [26]:
df[final_cols]

,sex,age,day,sleep,eatdrink,selfcare,paidwork,educatn,foodprep,cleanetc,...,volorgwk,commute,travel,sportex,tvradio,read,compint,goout,leisure,missing
293114,Woman,57.0,Monday,510.0,90.0,50.0,140.0,0.0,60.0,120.0,...,30.0,30.0,20.0,0.0,200.0,40.0,0.0,0.0,80.0,0.0
293115,Man,59.0,Monday,410.0,110.0,80.0,490.0,0.0,10.0,20.0,...,20.0,40.0,0.0,0.0,170.0,20.0,0.0,0.0,50.0,0.0
293116,Woman,81.0,Thursday,450.0,140.0,60.0,0.0,0.0,90.0,260.0,...,0.0,0.0,0.0,0.0,400.0,0.0,0.0,0.0,40.0,0.0
293117,Woman,81.0,Sunday,620.0,110.0,40.0,0.0,0.0,110.0,70.0,...,0.0,0.0,0.0,0.0,410.0,0.0,0.0,0.0,80.0,0.0
293118,Man,78.0,Friday,550.0,100.0,50.0,0.0,0.0,70.0,0.0,...,0.0,0.0,30.0,0.0,160.0,60.0,0.0,130.0,60.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321012,Woman,49.0,Sunday,480.0,120.0,40.0,0.0,0.0,80.0,150.0,...,0.0,0.0,130.0,0.0,260.0,0.0,0.0,0.0,60.0,0.0
321013,Man,59.0,Saturday,420.0,100.0,90.0,0.0,0.0,130.0,90.0,...,0.0,0.0,30.0,0.0,180.0,0.0,0.0,0.0,60.0,0.0
321014,Man,59.0,Friday,380.0,40.0,90.0,0.0,0.0,50.0,0.0,...,190.0,0.0,100.0,0.0,0.0,0.0,120.0,0.0,300.0,0.0
321015,Woman,54.0,Saturday,440.0,90.0,90.0,0.0,0.0,90.0,170.0,...,0.0,0.0,50.0,90.0,110.0,0.0,60.0,0.0,80.0,0.0
321016,Woman,54.0,Friday,510.0,310.0,150.0,0.0,0.0,50.0,90.0,...,0.0,0.0,50.0,20.0,60.0,0.0,30.0,0.0,30.0,0.0

In [7]:
df["survey"].value_counts()

survey
2009.0    27903
1985.0    16047
1998.0    15441
1974.0     4633
1966.0     2702
1961.0        0
1964.0        0
1965.0        0
1971.0        0
1975.0        0
1979.0        0
1980.0        0
1981.0        0
1983.0        0
1986.0        0
1987.0        0
1989.0        0
1990.0        0
1991.0        0
1992.0        0
1993.0        0
1995.0        0
1997.0        0
1999.0        0
2000.0        0
2001.0        0
2002.0        0
2003.0        0
2004.0        0
2005.0        0
2006.0        0
2007.0        0
2008.0        0
2010.0        0
2011.0        0
2012.0        0
2013.0        0
2014.0        0
2015.0        0
2016.0        0
2017.0        0
2018.0        0
2019.0        0
2020.0        0
2021.0        0
2022.0        0
2023.0        0
Name: count, dtype: int64